// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWqPtGAsx6kF6WR0UIFz45OMxSOLw182w',
    appId: '1:257026329569:android:0183ac8abbd5f01d3fe0a0',
    messagingSenderId: '257026329569',
    projectId: 'peerchat-95c0b',
    storageBucket: 'peerchat-95c0b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmMJWpPiMAI37JOqckipECF_bvP_d-Hq4',
    appId: '1:257026329569:ios:2bbe7d71870dc59c3fe0a0',
    messagingSenderId: '257026329569',
    projectId: 'peerchat-95c0b',
    storageBucket: 'peerchat-95c0b.firebasestorage.app',
    androidClientId: '257026329569-cert4psnuhu622mf9l8qvk740vn2gg6r.apps.googleusercontent.com',
    iosClientId: '257026329569-kt53lpmmnsh6ematf64tv12mo3pu7k2k.apps.googleusercontent.com',
    iosBundleId: 'app.peerchat.mathi',
  );

}